import Head from "next/head";

import Header from "@/components/admin/Header";
import Sidebar from "@/components/admin/Sidebar";
import Link from "next/link";
import { FaPen, FaTrashAlt } from "react-icons/fa";

export default function Admin() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Sidebar>
            <main className="bg-gray-100 min-h-screen">
               <Header title="Listado de comunidades" />
               <h1 className="text-4xl p-4 text-center">Comunidades</h1>
               <div className="relative overflow-x-auto shadow-md sm:rounded-lg m-4">
                  <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                     <thead className="text-sm text-gray-900 uppercase dark:text-gray-400 border border-b-gray-200 ">
                        <tr>
                           <th
                              scope="col"
                              className="px-6 py-3 bg-gray-50 dark:bg-gray-800"
                           >
                              ACCIONES
                           </th>
                           <th scope="col" className="px-6 py-3">
                              USUARIO
                           </th>
                           <th
                              scope="col"
                              className="px-6 py-3 bg-gray-50 dark:bg-gray-800"
                           >
                              NOMBRE
                           </th>
                           <th scope="col" className="px-6 py-3">
                              TELÉFONO
                           </th>
                           <th
                              scope="col"
                              className="px-6 py-3 bg-gray-50 dark:bg-gray-800"
                           >
                              CIF
                           </th>
                        </tr>
                     </thead>
                     <tbody>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente1@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Ramón Martínez
                           </td>
                           <td className="px-6 py-4">634 478 569</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              47159862R
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente2@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Ángela Cortes
                           </td>
                           <td className="px-6 py-4">767 069 864</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              41361535Z
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente3@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Rodrigo Ferrer
                           </td>
                           <td className="px-6 py-4">768 474 601</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              37718818Z
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente4@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Eduardo Garcia
                           </td>
                           <td className="px-6 py-4">757 650 889</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              49525113H
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente5@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Natalia Saez
                           </td>
                           <td className="px-6 py-4">720 719 468</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              65183393J
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente6@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Roberto Rodriguez
                           </td>
                           <td className="px-6 py-4">783 839 118</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              42921923J
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente7@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Aitor Torres
                           </td>
                           <td className="px-6 py-4">676 974 102</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              74028620S
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente8@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Eva María Saez
                           </td>
                           <td className="px-6 py-4">788 566 913</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              52271923F
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente9@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              María Rosario Santos
                           </td>
                           <td className="px-6 py-4">623 700 444</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              73564834R
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente10@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              María Ángeles Vidal
                           </td>
                           <td className="px-6 py-4">766 197 153</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              84457314A
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente11@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Carmen Saez
                           </td>
                           <td className="px-6 py-4">658 451 366</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              59774756X
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente12@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Sofía Rubio
                           </td>
                           <td className="px-6 py-4">678 249 053</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              96452684E
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente13@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Eduardo Molina
                           </td>
                           <td className="px-6 py-4">636 892 159</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              75549720X
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente14@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Noelia Nieto
                           </td>
                           <td className="px-6 py-4">774 640 530</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              77011829D
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente15@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              María Victoria Muñoz
                           </td>
                           <td className="px-6 py-4">730 760 770</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              12565630V
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente16@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Susana Medina
                           </td>
                           <td className="px-6 py-4">684 300 887</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              25970648Z
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente17@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Mohamed Rojas
                           </td>
                           <td className="px-6 py-4">676 744 330</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              08265945K
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente18@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Elena Montero
                           </td>
                           <td className="px-6 py-4">668 015 528</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              46011811N
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente19@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Alicia Moya
                           </td>
                           <td className="px-6 py-4">799 187 922</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              29841909F
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente20@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Catalina Blanco
                           </td>
                           <td className="px-6 py-4">744 843 767</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              15776499V
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente21@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Marta Pascual
                           </td>
                           <td className="px-6 py-4">752 630 414</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              61015981V
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente22@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Laura Latorre
                           </td>
                           <td className="px-6 py-4">722 630 004</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              69835981P
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente23@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Ángel Montoro
                           </td>
                           <td className="px-6 py-4">722 620 214</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              61000981K
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente24@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Marc Álvarez
                           </td>
                           <td className="px-6 py-4">762 621 114</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              90015313Q
                           </td>
                        </tr>
                        <tr className="border-b border-gray-200 dark:border-gray-700">
                           <th
                              scope="row"
                              className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800"
                           >
                              <div className="flex flex-row gap-4 ">
                                 <FaPen className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                                 <FaTrashAlt className="text-mainColor cursor-pointer text-lg hover:scale-125 transition duration-300" />
                              </div>
                           </th>
                           <td className="px-6 py-4">cliente25@ejemplo.com</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              Antonio Rodríguez
                           </td>
                           <td className="px-6 py-4">632 730 198</td>
                           <td className="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                              88078881L
                           </td>
                        </tr>
                     </tbody>
                  </table>
               </div>
            </main>
         </Sidebar>
      </>
   );
}
