import Head from 'next/head';

import Header from '@/components/client/Header';
import TopCards from '@/components/client/TopCards';
import BarChart from '@/components/client/BarChart';
import RecentOrders from '@/components/client/RecentOrders';
import Sidebar from '@/components/client/Sidebar';

export default function Client() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Sidebar>
                <main className='bg-gray-100 min-h-screen'>
                    <Header title="Resumen" />
                    <TopCards />
                    <div className='grid md:grid-cols-3 grid-cols-1 gap-4 mx-4 mb-4'>
                        <BarChart />
                        <RecentOrders />
                    </div>
                </main>
            </Sidebar>
        </>
    );
}
