import Head from 'next/head';

import Header from '@/components/admin/Header';
import Sidebar from '@/components/admin/Sidebar';
import Link from 'next/link';
import { FaPlus, FaFileExcel, FaPaperPlane } from "react-icons/fa";

export default function Alta() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Sidebar>
                <main className='bg-gray-100 min-h-screen'>
                    <Header title="Alta de comunidad" />
                    <h1 className='text-4xl p-4 text-center'>Elige la forma de alta</h1>
                    <div className="flex flex-col xl:grid xl:grid-cols-3 gap-4 p-4 mx-auto">
                        <Link href="/admin/alta/manual">
                            <div className='flex justify-center items-center flex-col gap-4 text-white rounded-3xl bg-mainColor p-28 shadow-md hover:shadow-lg transition duration-300'>
                                <FaPlus className='text-3xl' />
                                <h1 className='text-lg'>Alta manual</h1>
                            </div>
                        </Link>
                        <Link href="/admin/alta/csv">
                            <div className='flex justify-center items-center flex-col gap-4 text-white rounded-3xl bg-mainColor p-28 shadow-md hover:shadow-lg transition duration-300'>
                                <FaFileExcel className='text-3xl' />
                                <h1 className='text-lg'>Subir CSV</h1>
                            </div>
                        </Link>
                        <Link href="/admin/alta/traslado">
                            <div className='flex justify-center items-center flex-col gap-4 text-white rounded-3xl bg-mainColor p-28 shadow-md hover:shadow-lg transition duration-300'>
                                <FaPaperPlane className='text-3xl' />
                                <h1 className='text-lg'>Solicitar traslado</h1>
                            </div>
                        </Link>
                    </div>
                </main>
            </Sidebar>
        </>
    );
}
